logging:
  level:
    com.entdiy: INFO
    io.netty.handler.logging: INFO
    root: INFO
  config: classpath:logback-spring-dev.xml
nat:
  domain: nat.test.com
  httpAddr: 4440
  tunnelAddr: 4443
  clients:
    entdiy:
      secret: entdiy123
    test:
      secret: test123

